### ISSUE TITLE
I'm still getting set up, check back soon!

### ISSUE THREAD

**Issue by vinnitu** [kikinteractive/kik-node#2]
i register bot and get apiKey
running server with public domain
I can only send message to other (me as owner), but 
when I try to send some message to bot I have got
'I'm still getting set up, check back soon!'

What I need to do?

**Comment by marwanad** [comment]
Have you gone through the configuration steps mentioned [here](https://dev.kik.com/#/docs/messaging#configuration)?

**Comment by JonathanZWhite** [comment]
@vinnitu I actually had this same issue last night. Turns this was because I hadn't authenticated and registered my webhook. Checkout this line of code [here](https://github.com/JonathanZWhite/kik-bot-starterkit/blob/master/server.js#L17). 

If you want, you can also clone my [starterkit](https://github.com/JonathanZWhite/kik-bot-starterkit)

**Comment by JonathanZWhite** [comment]
@vinnitu so it turns out you don't need to make a POST request to `https://api.kik.com/v1/config`. Instead, you can simply call `bot.updateBotConfiguration()`. 

You can find an example of that [here](https://github.com/JonathanZWhite/kik-bot-starterkit/blob/master/server.js#L18). Also, you can see the method defined [here](https://github.com/kikinteractive/kik-node/blob/master/index.js#L201) by @kikinteractive.

**Comment by vinnitu** [comment]
Thanks. It works.
