### ISSUE TITLE
Cannot use bot.onTextMessage in one kik.onTextMessage

### ISSUE THREAD

**Issue by austinhuang0131** [kikinteractive/kik-node#34]
### Expected behavior
Reply `c` after sending `b` and receiving a reply
### Actual behavior
Does not reply `c`
### Environment Details
* Kik-Node 2.0.12
* Nodejs v7.0.0

### Steps to reproduce the behavior
```js
	bot.onTextMessage((message,next) => {
		if (message.body === "a") {
			message.reply("b");
			bot.onTextMessage((answer, txen) => {
				answer.reply("c");
			});
		}
	});
```
1. Send "a"
2. Receive reply: "b"
3. Send random text
4. Should receive "c" but didn't

**Comment by dozoisch** [comment]
What happens, is that when you send the random text if gets in your first onTextMessage. Which checks if the body === a. and else doesn't do anything (eg: next is not called). So you swallow the message down. 

Also, you shouldn't use nested handlers, because every time you will receive a, you will register a new handler and will end up with a lot of handlers.

**Comment by remvst** [comment]
Yeah I'm gonna close this as this is not even how you're supposed to use the library. This library does not provide flow/state machine features, so you would have to build that yourself.

Something like 
```javascript
bot.onTextMessage((message) => {
    let state = getUserCurrentState();
    if (state === 1) {
        message.reply('b');
        setUserState(2)
    } else if (state === 2) {
        message.reply('c')
    }
});
```

**Comment by austinhuang0131** [comment]
Tried but failed. #41
